/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import Banner from './banner'
// import Image from 'next/image'
import Section from './section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image src={'/home.png'} width={700} height={1500}/> */}
      <img src="/home.jpg" style={{width:1600,height:700}} alt="" />
      <Banner/>
      <Section/>
    </div>
  )
}
